@startuml
'https://plantuml.com/class-diagram
Class Element{
 String name
 String type
 Double price
 String getName()
 String getType()
 Double getPrice()
 void setPrice()
}

Class BoardElement{
 String designation
 Element element
 String getDesignation()
 Element getElement()
 void setElement
}

Class Board{
 List<BoardElement> elementsList
 List<BoardElement> getElementsList()
}

Class Unit{
 List<Board> boardsList
 List<Board> getBoardsList()
}

Class Product{
 List<Unit> unitsList
 List<Unit> getUnitsList()
 void addUnit(Unit newUnit)
}
@enduml